# Generated by Django 4.2.6 on 2023-10-23 06:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MockAuthorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('num_pages', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(0)])),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('reviews_count', models.IntegerField(default=0, validators=[django.core.validators.MinLengthValidator(0)])),
                ('ratings_count', models.IntegerField(default=0, validators=[django.core.validators.MinLengthValidator(0)])),
                ('average_ratings', models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('author', models.ManyToManyField(blank=True, null=True, to='book_collection.mockauthorprofile')),
                ('genre', models.ManyToManyField(blank=True, null=True, to='book_collection.genre')),
            ],
        ),
    ]