# Generated by Django 4.2.7 on 2023-11-20 07:39

from django.db import migrations
from django.core.management import call_command

def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "genres")
    call_command("loaddata", "authors")
    call_command("loaddata", "books")


class Migration(migrations.Migration):

    dependencies = [
        ('book_collection', '0002_book_author'),
        ('user_profile', '0002_profile_profile_picture_alter_profile_name'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]
