# Generated by Django 4.2.6 on 2023-10-26 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_collection', '0004_auto_20231023_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockauthorprofile',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
