# Generated by Django 4.2.6 on 2023-10-26 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_collection', '0005_mockauthorprofile_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mockauthorprofile',
            old_name='profile',
            new_name='user',
        ),
    ]
