# Generated by Django 4.2.6 on 2023-10-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_collection', '0008_alter_book_num_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='average_ratings',
        ),
        migrations.RemoveField(
            model_name='book',
            name='ratings_count',
        ),
        migrations.RemoveField(
            model_name='book',
            name='reviews_count',
        ),
        migrations.AlterField(
            model_name='book',
            name='num_pages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
