# Generated by Django 4.2.7 on 2023-11-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('genres', models.CharField(blank=True, max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True)),
                ('num_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('publish_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
