# Generated by Django 4.2.4 on 2023-10-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
