# Generated by Django 4.2.4 on 2023-10-28 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_collection', '0011_auto_20231028_1348'),
        ('user_profile', '0001_initial'),
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_collection.book'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='userProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile'),
        ),
    ]
