# Generated by Django 4.2.6 on 2023-10-28 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='userProfile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile'),
        ),
    ]
