# Generated by Django 4.2.6 on 2023-10-29 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_alter_leaderboard_book_alter_leaderboard_userprofile'),
        ('leaderboard', '0002_initial'),
    ]

    operations = [
    ]
