# Generated by Django 4.2.6 on 2023-10-29 06:56


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_collection', '0009_remove_book_average_ratings_and_more'),
        ('user_profile', '0002_profile_profile_picture_alter_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book_collection.book')),
                ('userProfile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile')),

            ],
        ),
    ]
