# Generated by Django 4.2.6 on 2023-10-29 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_collection', '0011_auto_20231028_1348'),
        ('review', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_collection.book'),
        ),
    ]
