<<<<<<< HEAD
# Generated by Django 4.2.4 on 2023-10-29 05:13
=======
# Generated by Django 4.2.6 on 2023-10-29 06:09
>>>>>>> 6d3179d39dafa36610d7da6711b6a605219c8ef5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
